### ISSUE TITLE
Is this released to rubygems.org? Couldn't find it  :( 

### ISSUE THREAD

**Issue by bogdanRada** [dariusgm/jasmine-reporter#2]
Please release this gem to rubygems :) or close this issue if you think this is not needed.Thanks

**Comment by bogdanRada** [comment]
nevermind. Seems this repository didn't had any activity in 2 years :( Thanks anyway .

**Comment by dariusgm** [comment]
Are there missing feature you would like to see? I did not add any feature, because everything that was needed, is there. You can add this Gem to your Gemfile without the need of rubygems by `gem 'jasmine-reporter', :git => 'https://github.com/dariusgm/jasmine-reporter.git'
`

**Comment by bogdanRada** [comment]
yes but if i am planning to create a gem to have as dependency this gem i wouldn't be able to add it as dependency . See my point ?
